export {
  DEFAULT_TRANSLATION_FOLDER,
  CONFIG_FILE_NAME,
  DEFAULT_DICTIONARIES,
  DEFAULT_ENVIRONMENT_DATA,
  DEFAULT_ENVIRONMENT_FOLDER,
  getFolder,
  initConfigs,
  getConfigs,
  getDictionaries,
  setConfigs,
  setDictionaries,
  getEnvironments,
  setEnvironments,
} from "./config";
