export {
  DEFAULT_TRANSLATION_FOLDER,
  CONFIG_FILE_NAME,
  DEFAULT_DICTIONARIES,
  DEFAULT_ENVIRONMENT_DATA,
  getFolder,
  getFeaturesFolder,
  initConfigs,
  removeConfigs,
  getConfigs,
  getDictionaries,
  setConfigs,
  setDictionaries,
  getEnvironments,
  setEnvironments,
  getConfigFilename,
  checkInit,
} from "./config";
